name = "master-checklist"
enable_secrets = true

allowed_usergroups = [
  "okta-team-applied-fte@applied.co",
  "okta-ext-frontier@applied.co",
  "okta-team-vehicle-testing@applied.co",
]

[cloudrun.env_vars]
CONFLUENCE_BOT_EMAIL = "john.pham@applied.co"

[metadata]
owner = "john.pham@applied.co"
